name: walpaper_app_api
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  # statemamegement
  get: ^4.6.6

  #  slider for images for various size
  flutter_staggered_grid_view: ^0.7.0
  #for http
  http: ^1.3.0
  dio: ^5.8.0+1
  # for permisson and storgae manager:
  permission_handler: ^11.3.1
  path_provider: ^2.1.5

  # loaging
  flutter_easyloading: ^3.0.5

  # for gallary save
  gallery_saver_updated: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
